<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fin</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Finch</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.finch</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(').*$\n?</string>
			<key>name</key>
			<string>comment.line.finch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-?\b[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.finch</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.finch</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.finch</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(&lt;-|&lt;--|::)(?=\s|^)</string>
			<key>name</key>
			<string>keyword.language.finch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(self|undefined)(?=\s|^)</string>
			<key>name</key>
			<string>constant.language.finch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)(#PRIM#|True|False|Nil)(?=\s|^)</string>
			<key>name</key>
			<string>variable.language.finch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)[\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*]+(?=\s|^)</string>
			<key>name</key>
			<string>keyword.operator.user.finch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)[A-Za-z0-9\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*_]*\:</string>
			<key>name</key>
			<string>keyword.user.finch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)[\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*]*[A-Z]+[A-Za-z0-9\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*_]*</string>
			<key>name</key>
			<string>variable.global.finch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s|^)[\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*]*_+[A-Za-z0-9\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*_]*</string>
			<key>name</key>
			<string>variable.object.finch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\(\)\[\]\{\}\;\,\.]</string>
			<key>name</key>
			<string>punctuation.finch</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\|</string>
			<key>end</key>
			<string>\|</string>
			<key>name</key>
			<string>meta.parameter-list.finch</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*_]+</string>
					<key>name</key>
					<string>variable.parameter.finch</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.finch</string>
	<key>uuid</key>
	<string>68B06728-9743-40E3-842E-E1B0E907FCEC</string>
</dict>
</plist>
